---
name: Práctica Primeros Programas
locale: es
type: practice
beta: false
teacher_info: ''
language: gobstones
id_format: "%05d"
order:
- 900
- 1000
- 1100
- 1401
- 1200
- 1402
- 1403
- 1400
- 1404
